# Generated by Django 5.2.5 on 2025-09-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="subtask",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "SubTask",
                "verbose_name_plural": "SubTasks",
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
        migrations.AlterUniqueTogether(
            name="task",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(
                max_length=100,
                unique_for_date="created_at",
                verbose_name="Название задачи",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_category_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="subtask",
            constraint=models.UniqueConstraint(
                fields=("title",), name="unique_subtask_title"
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                fields=("title",), name="unique_task_title"
            ),
        ),
        migrations.AlterModelTable(
            name="category",
            table="task_manager_category",
        ),
        migrations.AlterModelTable(
            name="subtask",
            table="task_manager_subtask",
        ),
        migrations.AlterModelTable(
            name="task",
            table="task_manager_task",
        ),
    ]
