# Generated by Django 5.2.5 on 2025-10-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0004_subtask_owner_task_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="last_notified_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
